# Generated by Django 5.0.6 on 2024-06-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music_detailing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("summary", models.CharField(max_length=100)),
                ("artist", models.CharField(max_length=50)),
                ("country_list", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="musicdetails",
            name="artist",
        ),
        migrations.DeleteModel(
            name="Artist",
        ),
        migrations.DeleteModel(
            name="MusicDetails",
        ),
    ]
