# Generated by Django 5.0.6 on 2024-06-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "music_detailing",
            "0002_song_remove_musicdetails_artist_delete_artist_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="country_list",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="song",
            name="summary",
            field=models.TextField(),
        ),
    ]
